# the value of noprefetch will be replaced during benchmarking
noprefetch = true
debug_address = "/run/containerd-stargz-grpc/debug.sock"

[[resolver.host."192.168.0.18:5000".mirrors]]
host = "192.168.0.18:5000"
insecure = true

[[resolver.host."192.168.0.254:5000".mirrors]]
host = "192.168.0.254:5000"
insecure = true

[[resolver.host."10.17.16.23:5000".mirrors]]
host = "10.17.16.23:5000"
insecure = true